services: 
    homeassistant: 
        container_name: homeassistant 
        image: "ghcr.io/home-assistant/home-assistant:stable"
        environment: 
            - TZ=Europe/Moscow
        volumes: 
            - ./config:/config
        restart: unless-stopped 
        privileged: true 
        devices: 
            - /dev/ttyUSB0:/dev/ttyUSB0
        ports:
            - 8123:8123
        networks: 
            - ha_net 
    plugcontrolservice:
        container_name: proxyapi
        image: "do6ryjkot/ha-plug-control-service"
        ports: 
            - 35000:8080
        environment: 
            HA_KEY: "<key>"
            HA_API_BASE_URL: "http://homeassistant:8123"
            HA_API_ENDP_TURNON: "api/services/switch/turn_on"
            HA_API_ENDP_TURNOFF: "api/services/switch/turn_off"
        depends_on: 
            - homeassistant
        networks:
            - ha_net
networks:
    ha_net: